- name: create admin group
  group: name=admin gid=1100 system=no
  become: true
  tags: sshkey

- name: create user
  user: name=informatica state=present group=admin shell=/bin/bash uid=1000
  become: true
  tags: sshkey

- name: setup authorized key
  authorized_key: user=informatica key="{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: true
  tags:
    - sshkey

- name: write the sudoers file custom
  template: src=custom_sudo.j2 dest=/etc/sudoers.d/custom
           owner=root group=root mode=0400
  become: true
  tags:
    - sshkey